flowchart LR
    User(("User"))
    style User fill:#e1f5ff,stroke:#0288d1,stroke-width:3px,color:#000

    ManajemenTestimonial(("Manajemen Testimonial"))
    ManajemenProjectGallery(("Manajemen Project Gallery"))

    Login(("Login"))

    User --> ManajemenTestimonial
    User --> ManajemenProjectGallery

    ManajemenTestimonial -.->|"#lt;#lt;include#gt;#gt;"| Login
    ManajemenProjectGallery -.->|"#lt;#lt;include#gt;#gt;"| Login
